from selenium.webdriver.common.by import By
from src.testproject.classes import DriverStepSettings, StepSettings
from src.testproject.decorator import report_assertion_errors
from src.testproject.enums import SleepTimingType
from src.testproject.enums import TakeScreenshotConditionType
from src.testproject.sdk.drivers import webdriver
import pytest


"""
This pytest test was automatically generated by TestProject
    Project: VLFsports
    Package: TestProject.Generated.Tests.VLFsports
    Test: CP-07A
    Generated by: Carlos Leonardo (thorin.1620@gmail.com)
    Generated on 04/04/2022, 03:53:49
"""


@pytest.fixture()
def driver():
    driver = webdriver.Chrome(token="w0FakVRmj9dNXYcKJPUnZ09uKCtFIu24ziWZm9gCuAE",
                              project_name="VLFsports",
                              job_name="CP-07A")
    step_settings = StepSettings(timeout=15000,
                                 sleep_time=500,
                                 sleep_timing_type=SleepTimingType.Before)
    with DriverStepSettings(driver, step_settings):
        yield driver
    driver.quit()


@report_assertion_errors
def test_main(driver):
    """Validación código de descuento nuevo."""
    # Test Parameters
    # Auto generated application URL parameter
    ApplicationURL = "https://vlfsports.odoo.com"
    promo = ""

    # 1. Navigate to '{ApplicationURL}'
    # Navigates the specified URL (Auto-generated)
    driver.get(f'{ApplicationURL}')

    # 2. Click 'Tienda'
    tienda = driver.find_element(By.XPATH,
                                 "//span[. = 'Tienda']")
    tienda.click()

    # 3. Click 'IMG2'
    img2 = driver.find_element(By.XPATH,
                               "//tr[1]/td[1]//img")
    img2.click()

    # 4. Click 'I6'
    i6 = driver.find_element(By.XPATH,
                             "//div[1]/div[2]/a/i")
    i6.click()

    # 5. Click 'I6'
    i6 = driver.find_element(By.XPATH,
                             "//div[1]/div[2]/a/i")
    i6.click()

    # 6. Click 'I6'
    i6 = driver.find_element(By.XPATH,
                             "//div[1]/div[2]/a/i")
    i6.click()

    # 7. Click 'ADD TO CART1'
    add_to_cart1 = driver.find_element(By.XPATH,
                                       "//span[. = 'ADD TO CART']")
    add_to_cart1.click()

    # 8. Click '41'
    _41 = driver.find_element(By.XPATH,
                              "//sup[. = '4']")
    _41.click()

    # 9. Click 'Tengo un código promocional'
    tengo_un_c_digo_promocional = driver.find_element(By.XPATH,
                                                      "//a[. = 'Tengo un código promocional']")
    tengo_un_c_digo_promocional.click()

    # 10. Click 'promo'
    promo = driver.find_element(By.CSS_SELECTOR,
                                "[name='promo']")
    promo.click()

    # 11. Type '{promo}' in 'promo'
    promo = driver.find_element(By.CSS_SELECTOR,
                                "[name='promo']")
    promo.send_keys(f'{promo}')

    # 12. Click 'Aplicar'
    aplicar = driver.find_element(By.XPATH,
                                  "//a[. = 'Aplicar']")
    aplicar.click()

    # 13. Click 'promo'
    step_settings = StepSettings(screenshot_condition=TakeScreenshotConditionType.Always,
                                 always_pass=True)
    with DriverStepSettings(driver, step_settings):
        promo = driver.find_element(By.CSS_SELECTOR,
                                    "[name='promo']")
        promo.click()
