from selenium.webdriver.common.by import By
from src.testproject.classes import DriverStepSettings, StepSettings
from src.testproject.decorator import report_assertion_errors
from src.testproject.enums import SleepTimingType
from src.testproject.enums import TakeScreenshotConditionType
from src.testproject.sdk.drivers import webdriver
import pytest


"""
This pytest test was automatically generated by TestProject
    Project: VLFsports
    Package: TestProject.Generated.Tests.VLFsports
    Test: CP-04B
    Generated by: Carlos Leonardo (thorin.1620@gmail.com)
    Generated on 04/04/2022, 03:53:13
"""


@pytest.fixture()
def driver():
    driver = webdriver.Chrome(token="w0FakVRmj9dNXYcKJPUnZ09uKCtFIu24ziWZm9gCuAE",
                              project_name="VLFsports",
                              job_name="CP-04B")
    step_settings = StepSettings(timeout=15000,
                                 sleep_time=500,
                                 sleep_timing_type=SleepTimingType.Before)
    with DriverStepSettings(driver, step_settings):
        yield driver
    driver.quit()


@report_assertion_errors
def test_main(driver):
    """Vaciar Carrito."""
    # Test Parameters
    # Auto generated application URL parameter
    ApplicationURL = "https://vlfsports.odoo.com"

    # 1. Navigate to '{ApplicationURL}'
    # Navigates the specified URL (Auto-generated)
    driver.get(f'{ApplicationURL}')

    # 2. Click 'Tienda'
    tienda = driver.find_element(By.XPATH,
                                 "//span[. = 'Tienda']")
    tienda.click()

    # 3. Click 'IMG1'
    img1 = driver.find_element(By.XPATH,
                               "//tr[1]/td[3]//img")
    img1.click()

    # 4. Click 'I6'
    i6 = driver.find_element(By.XPATH,
                             "//div[1]/div[2]/a/i")
    i6.click()

    # 5. Click 'ADD TO CART1'
    add_to_cart1 = driver.find_element(By.XPATH,
                                       "//span[. = 'ADD TO CART']")
    add_to_cart1.click()

    # 6. Click '21'
    _21 = driver.find_element(By.XPATH,
                              "//sup[. = '2']")
    _21.click()

    # 7. Click 'I7'
    step_settings = StepSettings(
        screenshot_condition=TakeScreenshotConditionType.Always)
    with DriverStepSettings(driver, step_settings):
        i7 = driver.find_element(By.XPATH,
                                 "//small/i")
        i7.click()
