from selenium.webdriver.common.by import By
from src.testproject.classes import DriverStepSettings, StepSettings
from src.testproject.decorator import report_assertion_errors
from src.testproject.enums import SleepTimingType
from src.testproject.enums import TakeScreenshotConditionType
from src.testproject.sdk.drivers import webdriver
import pytest


"""
This pytest test was automatically generated by TestProject
    Project: VLFsports
    Package: TestProject.Generated.Tests.VLFsports
    Test: CP-01A
    Generated by: Carlos Leonardo (thorin.1620@gmail.com)
    Generated on 04/04/2022, 03:51:52
"""


@pytest.fixture()
def driver():
    driver = webdriver.Chrome(token="w0FakVRmj9dNXYcKJPUnZ09uKCtFIu24ziWZm9gCuAE",
                              project_name="VLFsports",
                              job_name="CP-01A")
    step_settings = StepSettings(timeout=15000,
                                 sleep_time=500,
                                 sleep_timing_type=SleepTimingType.Before)
    with DriverStepSettings(driver, step_settings):
        yield driver
    driver.quit()


@report_assertion_errors
def test_main(driver):
    """ACCESO EXITOSO."""
    # Test Parameters
    # Auto generated application URL parameter
    ApplicationURL = "https://vlfsports.odoo.com"
    usuario = "migue130901@gmail.com"
    contrasena = "Lukas130901"

    # 1. Navigate to '{ApplicationURL}'
    # Navigates the specified URL (Auto-generated)
    driver.get(f'{ApplicationURL}')

    # 2. Click 'Identificarse'
    identificarse = driver.find_element(By.XPATH,
                                        "//a[. = 'Identificarse']")
    identificarse.click()

    # 3. Click 'login'
    login = driver.find_element(By.CSS_SELECTOR,
                                "#login")
    login.click()

    # 4. Type '{usuario}' in 'login'
    login = driver.find_element(By.CSS_SELECTOR,
                                "#login")
    login.send_keys(f'{usuario}')

    # 5. Click 'password'
    password = driver.find_element(By.CSS_SELECTOR,
                                   "#password")
    password.click()

    # 6. Type '{contrasena}' in 'password'
    password = driver.find_element(By.CSS_SELECTOR,
                                   "#password")
    password.send_keys(f'{contrasena}')

    # 7. Click 'Iniciar sesión'
    iniciar_sesi_n = driver.find_element(By.XPATH,
                                         "//button[. = 'Iniciar sesión']")
    iniciar_sesi_n.click()

    # 8. Click 'DIV'
    step_settings = StepSettings(
        screenshot_condition=TakeScreenshotConditionType.Always)
    with DriverStepSettings(driver, step_settings):
        div = driver.find_element(By.XPATH,
                                  "//a[6]/div[1]")
        div.click()
