from selenium.webdriver.common.by import By
from src.testproject.classes import DriverStepSettings, StepSettings
from src.testproject.decorator import report_assertion_errors
from src.testproject.enums import SleepTimingType
from src.testproject.sdk.drivers import webdriver
import pytest


"""
This pytest test was automatically generated by TestProject
    Project: VLFsports
    Package: TestProject.Generated.Tests.VLFsports
    Test: CP-04A
    Generated by: Carlos Leonardo (thorin.1620@gmail.com)
    Generated on 04/04/2022, 03:53:03
"""


@pytest.fixture()
def driver():
    driver = webdriver.Chrome(token="w0FakVRmj9dNXYcKJPUnZ09uKCtFIu24ziWZm9gCuAE",
                              project_name="VLFsports",
                              job_name="CP-04A")
    step_settings = StepSettings(timeout=15000,
                                 sleep_time=500,
                                 sleep_timing_type=SleepTimingType.Before)
    with DriverStepSettings(driver, step_settings):
        yield driver
    driver.quit()


@report_assertion_errors
def test_main(driver):
    """Editar cantidad de productos."""
    # Test Parameters
    # Auto generated application URL parameter
    ApplicationURL = "https://vlfsports.odoo.com"

    # 1. Navigate to '{ApplicationURL}'
    # Navigates the specified URL (Auto-generated)
    driver.get(f'{ApplicationURL}')

    # 2. Click 'Tienda'
    tienda = driver.find_element(By.XPATH,
                                 "//span[. = 'Tienda']")
    tienda.click()

    # 3. Click 'Guantes de Boxeo'
    guantes_de_boxeo = driver.find_element(By.XPATH,
                                           "//a[. = 'Guantes de Boxeo']")
    guantes_de_boxeo.click()

    # 4. Click 'ADD TO CART'
    add_to_cart = driver.find_element(By.CSS_SELECTOR,
                                      "#add_to_cart")
    add_to_cart.click()

    # 5. Click 'I4'
    i4 = driver.find_element(By.XPATH,
                             "//li/a/i")
    i4.click()

    # 6. Click ''
    _ = driver.find_element(By.XPATH,
                            "//div[2]/a[. = '\n                                                \n                                            ']")
    _.click()

    # 7. Click '2'
    _2 = driver.find_element(By.XPATH,
                             "//div[2]/a[. = '\n                                                \n                                            ']")
    _2.click()
