from selenium.webdriver.common.by import By
from src.testproject.classes import DriverStepSettings, StepSettings
from src.testproject.decorator import report_assertion_errors
from src.testproject.enums import SleepTimingType
from src.testproject.enums import TakeScreenshotConditionType
from src.testproject.sdk.drivers import webdriver
import pytest


"""
This pytest test was automatically generated by TestProject
    Project: VLFsports
    Package: TestProject.Generated.Tests.VLFsports
    Test: CP-03A
    Generated by: Carlos Leonardo (thorin.1620@gmail.com)
    Generated on 04/04/2022, 03:52:43
"""


@pytest.fixture()
def driver():
    driver = webdriver.Chrome(token="w0FakVRmj9dNXYcKJPUnZ09uKCtFIu24ziWZm9gCuAE",
                              project_name="VLFsports",
                              job_name="CP-03A")
    step_settings = StepSettings(timeout=15000,
                                 sleep_time=500,
                                 sleep_timing_type=SleepTimingType.Before)
    with DriverStepSettings(driver, step_settings):
        yield driver
    driver.quit()


@report_assertion_errors
def test_main(driver):
    """Filtrar productos por parámetros."""
    # Test Parameters
    # Auto generated application URL parameter
    ApplicationURL = "https://vlfsports.odoo.com"

    # 1. Navigate to '{ApplicationURL}'
    # Navigates the specified URL (Auto-generated)
    driver.get(f'{ApplicationURL}')

    # 2. Click 'Tienda'
    tienda = driver.find_element(By.XPATH,
                                 "//span[. = 'Tienda']")
    tienda.click()

    # 3. Click 'Featured1'
    featured1 = driver.find_element(By.XPATH,
                                    "//span/span[. = 'Featured']")
    featured1.click()

    # 4. Click 'Name (A-Z)'
    step_settings = StepSettings(
        screenshot_condition=TakeScreenshotConditionType.Always)
    with DriverStepSettings(driver, step_settings):
        name_a_z_ = driver.find_element(By.XPATH,
                                        "//span[. = 'Name (A-Z)']")
        name_a_z_.click()

    # 5. Click 'Balon Rugby1'
    balon_rugby1 = driver.find_element(By.XPATH,
                                       "//a[. = 'Balon Rugby']")
    balon_rugby1.click()

    # 6. Click 'Balon Rugby2'
    balon_rugby2 = driver.find_element(By.XPATH,
                                       "//h1[. = 'Balon Rugby']")
    balon_rugby2.click()

    # 7. Click 'Balon Rugby2'
    step_settings = StepSettings(
        screenshot_condition=TakeScreenshotConditionType.Always)
    with DriverStepSettings(driver, step_settings):
        balon_rugby2 = driver.find_element(By.XPATH,
                                           "//h1[. = 'Balon Rugby']")
        balon_rugby2.click()
