from selenium.webdriver.common.by import By
from src.testproject.classes import DriverStepSettings, StepSettings
from src.testproject.decorator import report_assertion_errors
from src.testproject.enums import SleepTimingType
from src.testproject.sdk.drivers import webdriver
import pytest


"""
This pytest test was automatically generated by TestProject
    Project: VLFsports
    Package: TestProject.Generated.Tests.VLFsports
    Test: CP-05A
    Generated by: Carlos Leonardo (thorin.1620@gmail.com)
    Generated on 04/04/2022, 04:00:55
"""


@pytest.fixture()
def driver():
    driver = webdriver.Chrome(token="w0FakVRmj9dNXYcKJPUnZ09uKCtFIu24ziWZm9gCuAE",
                              project_name="VLFsports",
                              job_name="CP-05A")
    step_settings = StepSettings(timeout=15000,
                                 sleep_time=500,
                                 sleep_timing_type=SleepTimingType.Before)
    with DriverStepSettings(driver, step_settings):
        yield driver
    driver.quit()


@report_assertion_errors
def test_main(driver):
    """Validación campos formulario de Carrito."""
    # Test Parameters
    # Auto generated application URL parameter
    ApplicationURL = "https://vlfsports.odoo.com"
    nombre = ""
    correo = ""
    calle = ""
    ciudad = ""
    codpostal = ""
    telefono = ""

    # 1. Navigate to '{ApplicationURL}'
    # Navigates the specified URL (Auto-generated)
    driver.get(f'{ApplicationURL}')

    # 2. Click 'Tienda'
    tienda = driver.find_element(By.XPATH,
                                 "//span[. = 'Tienda']")
    tienda.click()

    # 3. Click 'SPAN2'
    span2 = driver.find_element(By.XPATH,
                                "//tr[1]/td[1]/div/form/div[2]/div[2]/div[1]//span")
    span2.click()

    # 4. Click 'I4'
    i4 = driver.find_element(By.XPATH,
                             "//li/a/i")
    i4.click()

    # 5. Click 'Pagar ahora'
    pagar_ahora = driver.find_element(By.XPATH,
                                      "//div[2]/div//span[. = 'Pagar ahora']")
    pagar_ahora.click()

    # 6. Click 'name'
    name = driver.find_element(By.CSS_SELECTOR,
                               "[name='name']")
    name.click()

    # 7. Type '{nombre}' in 'name'
    name = driver.find_element(By.CSS_SELECTOR,
                               "[name='name']")
    name.send_keys(f'{nombre}')

    # 8. Click 'email'
    email = driver.find_element(By.CSS_SELECTOR,
                                "[name='email']")
    email.click()

    # 9. Type '{correo}' in 'email'
    email = driver.find_element(By.CSS_SELECTOR,
                                "[name='email']")
    email.send_keys(f'{correo}')

    # 10. Click 'phone'
    phone = driver.find_element(By.CSS_SELECTOR,
                                "[name='phone']")
    phone.click()

    # 11. Type '{telefono}' in 'phone'
    phone = driver.find_element(By.CSS_SELECTOR,
                                "[name='phone']")
    phone.send_keys(f'{telefono}')

    # 12. Click 'street'
    street = driver.find_element(By.CSS_SELECTOR,
                                 "[name='street']")
    street.click()

    # 13. Type '{calle}' in 'street'
    street = driver.find_element(By.CSS_SELECTOR,
                                 "[name='street']")
    street.send_keys(f'{calle}')

    # 14. Click 'city'
    city = driver.find_element(By.CSS_SELECTOR,
                               "[name='city']")
    city.click()

    # 15. Type '{ciudad}' in 'city'
    city = driver.find_element(By.CSS_SELECTOR,
                               "[name='city']")
    city.send_keys(f'{ciudad}')

    # 16. Click 'zip'
    zip = driver.find_element(By.CSS_SELECTOR,
                              "[name='zip']")
    zip.click()

    # 17. Type '{codpostal}' in 'zip'
    zip = driver.find_element(By.CSS_SELECTOR,
                              "[name='zip']")
    zip.send_keys(f'{codpostal}')

    # 18. Click 'Siguiente'
    siguiente = driver.find_element(By.XPATH,
                                    "//span[. = 'Siguiente']")
    siguiente.click()

    # 19. Click 'o_payment_submit_button'
    o_payment_submit_button = driver.find_element(By.CSS_SELECTOR,
                                                  "[name='o_payment_submit_button']")
    o_payment_submit_button.click()
